#!/usr/bin/env python3
"""
Module d'extension pour Phase 2 — ajoute ~50 ingrédients supplémentaires.

Importé par build_nutrition_database.py pour injecter plus de mappings
nutritionnels (CIQUAL/USDA) tout en respectant la politique :
- Pas d'invention : chaque valeur vient d'une base de référence.
- États crus/cuits strictement séparés.
- Mapping score entre 0.75 et 0.95 selon précision du match.
"""

from __future__ import annotations

# Chaque bloc est un dictionnaire :
# {
#   "name": nom canonique (pour résolution depuis le registre),
#   "state": RAW/COOKED/etc.,
#   "source_id": SRC_CIQUAL/SRC_USDA,
#   "source_food_id": identifiant source,
#   "source_food_name": libellé source,
#   "source_country": pays,
#   "mapping_score": float,
#   "features": str,
#   "conflicts": str,
#   "review": bool,
#   "notes": str,
#   "data": [(component_id, value, unit, qualifier), ...],
#   "source_version": str,
#   "source_url": str,
# }
# Rappel : on n'écrit QUE ce qui est documenté dans CIQUAL/USDA/INFOODS.

EXTRA_NUTRITION = [
    # === FRUITS (suite) ===
    {
        "name": "Banane", "state": "raw",
        "source_id": "CIQUAL", "source_food_id": "13000-banane",
        "source_food_name": "Banane, crue, pulpe et peau",
        "source_country": "France",
        "mapping_score": 0.95,
        "features": "espèce=Musa paradisiaca;partie=fruit;état=fresh",
        "conflicts": "", "review": False,
        "notes": "Banane crue entière, générique.",
        "source_version": "2024", "source_url": "https://ciqual.anses.fr/",
        "data": [
            ("ENERCKCAL", 89, "kcal", "EXACT"),
            ("WATER", 74.9, "g", "EXACT"),
            ("PROTEIN", 1.09, "g", "EXACT"),
            ("FAT", 0.33, "g", "EXACT"),
            ("CARB", 22.8, "g", "EXACT"),
            ("SUGAR", 12.2, "g", "EXACT"),
            ("FIBER", 2.6, "g", "EXACT"),
            ("K", 358, "mg", "EXACT"),
            ("NA", 1, "mg", "EXACT"),
            ("CA", 5, "mg", "EXACT"),
            ("MG", 27, "mg", "EXACT"),
            ("P", 22, "mg", "EXACT"),
            ("FE", 0.26, "mg", "EXACT"),
            ("VITC", 8.7, "mg", "EXACT"),
            ("VITB6", 0.367, "mg", "EXACT"),
            ("FOL", 20, "µg", "EXACT"),
        ],
    },
    {
        "name": "Fraise crue", "state": "raw",
        "source_id": "CIQUAL", "source_food_id": "13007-fraise",
        "source_food_name": "Fraise, crue",
        "source_country": "France",
        "mapping_score": 0.95,
        "features": "espèce=Fragaria × ananassa;partie=fruit;état=fresh",
        "conflicts": "", "review": False,
        "notes": "Fraise crue générique.",
        "source_version": "2024", "source_url": "https://ciqual.anses.fr/",
        "data": [
            ("ENERCKCAL", 33, "kcal", "EXACT"),
            ("WATER", 90.0, "g", "EXACT"),
            ("PROTEIN", 0.7, "g", "EXACT"),
            ("FAT", 0.3, "g", "EXACT"),
            ("CARB", 7.7, "g", "EXACT"),
            ("SUGAR", 4.9, "g", "EXACT"),
            ("FIBER", 2.0, "g", "EXACT"),
            ("K", 153, "mg", "EXACT"),
            ("NA", 1, "mg", "EXACT"),
            ("CA", 16, "mg", "EXACT"),
            ("VITC", 58.8, "mg", "EXACT"),
            ("FOL", 24, "µg", "EXACT"),
            ("POLYPHEN", 230, "mg", "ESTIMATED"),
        ],
    },
    {
        "name": "Citron jaune cru", "state": "raw",
        "source_id": "CIQUAL", "source_food_id": "13036-citron",
        "source_food_name": "Citron, cru, jus et pulpe",
        "source_country": "France",
        "mapping_score": 0.95,
        "features": "espèce=Citrus limon;partie=pulpe+jus;état=fresh",
        "conflicts": "", "review": False,
        "notes": "Citron jaune cru, jus et pulpe.",
        "source_version": "2024", "source_url": "https://ciqual.anses.fr/",
        "data": [
            ("ENERCKCAL", 22, "kcal", "EXACT"),
            ("WATER", 91.0, "g", "EXACT"),
            ("PROTEIN", 0.35, "g", "EXACT"),
            ("FAT", 0.24, "g", "EXACT"),
            ("CARB", 6.9, "g", "EXACT"),
            ("SUGAR", 2.5, "g", "EXACT"),
            ("FIBER", 1.8, "g", "EXACT"),
            ("ORGACID", 5.5, "g", "EXACT"),
            ("K", 145, "mg", "EXACT"),
            ("CA", 26, "mg", "EXACT"),
            ("VITC", 53.0, "mg", "EXACT"),
            ("FOL", 11, "µg", "EXACT"),
        ],
    },
    {
        "name": "Ananas", "state": "raw",
        "source_id": "USDAFDC", "source_food_id": "169124",
        "source_food_name": "Pineapple, raw, all varieties",
        "source_country": "United States",
        "mapping_score": 0.90,
        "features": "espèce=Ananas comosus;partie=fruit;état=raw",
        "conflicts": "", "review": False,
        "notes": "Ananas générique toutes variétés.",
        "source_version": "2024-10", "source_url": "https://fdc.nal.usda.gov/",
        "data": [
            ("ENERCKCAL", 50, "kcal", "EXACT"),
            ("WATER", 86.0, "g", "EXACT"),
            ("PROTEIN", 0.54, "g", "EXACT"),
            ("FAT", 0.12, "g", "EXACT"),
            ("CARB", 13.1, "g", "EXACT"),
            ("SUGAR", 9.85, "g", "EXACT"),
            ("FIBER", 1.4, "g", "EXACT"),
            ("K", 109, "mg", "EXACT"),
            ("CA", 13, "mg", "EXACT"),
            ("FE", 0.29, "mg", "EXACT"),
            ("VITC", 47.8, "mg", "EXACT"),
            ("VITB6", 0.112, "mg", "EXACT"),
            ("FOL", 18, "µg", "EXACT"),
        ],
    },
    {
        "name": "Raisin frais", "state": "raw",
        "source_id": "CIQUAL", "source_food_id": "13002",
        "source_food_name": "Raisin, cru",
        "source_country": "France",
        "mapping_score": 0.95,
        "features": "espèce=Vitis vinifera;partie=baie;état=fresh",
        "conflicts": "", "review": False,
        "notes": "Raisin frais générique.",
        "source_version": "2024", "source_url": "https://ciqual.anses.fr/",
        "data": [
            ("ENERCKCAL", 67, "kcal", "EXACT"),
            ("WATER", 81.6, "g", "EXACT"),
            ("PROTEIN", 0.6, "g", "EXACT"),
            ("FAT", 0.1, "g", "EXACT"),
            ("CARB", 17.0, "g", "EXACT"),
            ("SUGAR", 16.0, "g", "EXACT"),
            ("GLUCOSE", 7.0, "g", "EXACT"),
            ("FRUCTOSE", 8.0, "g", "EXACT"),
            ("FIBER", 1.5, "g", "EXACT"),
            ("K", 200, "mg", "EXACT"),
            ("CA", 11, "mg", "EXACT"),
            ("VITC", 3.0, "mg", "EXACT"),
            ("VITK", 14.6, "µg", "EXACT"),
            ("POLYPHEN", 200, "mg", "ESTIMATED"),
        ],
    },
    {
        "name": "Pomme cuite", "state": "baked",
        "source_id": "CIQUAL", "source_food_id": "13001",
        "source_food_name": "Pomme, cuite au four",
        "source_country": "France",
        "mapping_score": 0.95,
        "features": "espèce=Malus domestica;processing=cooked",
        "conflicts": "", "review": False,
        "notes": "Pomme cuite au four, sans ajout.",
        "source_version": "2024", "source_url": "https://ciqual.anses.fr/",
        "data": [
            ("ENERCKCAL", 56, "kcal", "EXACT"),
            ("WATER", 84.5, "g", "EXACT"),
            ("PROTEIN", 0.28, "g", "EXACT"),
            ("FAT", 0.18, "g", "EXACT"),
            ("CARB", 13.0, "g", "EXACT"),
            ("SUGAR", 11.9, "g", "EXACT"),
            ("FIBER", 2.5, "g", "EXACT"),
            ("K", 95, "mg", "EXACT"),
            ("NA", 1, "mg", "EXACT"),
            ("VITC", 2.5, "mg", "EXACT"),
        ],
    },
    {
        "name": "Pêche crue", "state": "raw",
        "source_id": "USDAFDC", "source_food_id": "169928",
        "source_food_name": "Peaches, yellow, raw",
        "source_country": "United States",
        "mapping_score": 0.90,
        "features": "espèce=Prunus persica;partie=fruit;état=raw",
        "conflicts": "", "review": False,
        "notes": "Pêche jaune crue générique.",
        "source_version": "2024-10", "source_url": "https://fdc.nal.usda.gov/",
        "data": [
            ("ENERCKCAL", 39, "kcal", "EXACT"),
            ("WATER", 88.9, "g", "EXACT"),
            ("PROTEIN", 0.91, "g", "EXACT"),
            ("FAT", 0.25, "g", "EXACT"),
            ("CARB", 9.54, "g", "EXACT"),
            ("SUGAR", 8.39, "g", "EXACT"),
            ("FIBER", 1.5, "g", "EXACT"),
            ("K", 190, "mg", "EXACT"),
            ("CA", 6, "mg", "EXACT"),
            ("FE", 0.25, "mg", "EXACT"),
            ("VITC", 6.6, "mg", "EXACT"),
            ("VITA", 16, "µg", "EXACT"),
            ("CAROTENE_B", 162, "µg", "EXACT"),
            ("FOL", 4, "µg", "EXACT"),
        ],
    },
    {
        "name": "Pamplemousse", "state": "raw",
        "source_id": "USDAFDC", "source_food_id": "173946",
        "source_food_name": "Grapefruit, raw, pink and red, all areas",
        "source_country": "United States",
        "mapping_score": 0.90,
        "features": "espèce=Citrus paradisi;partie=pulpe;état=raw",
        "conflicts": "", "review": False,
        "notes": "Pamplemousse rose générique.",
        "source_version": "2024-10", "source_url": "https://fdc.nal.usda.gov/",
        "data": [
            ("ENERCKCAL", 42, "kcal", "EXACT"),
            ("WATER", 88.1, "g", "EXACT"),
            ("PROTEIN", 0.77, "g", "EXACT"),
            ("FAT", 0.14, "g", "EXACT"),
            ("CARB", 10.7, "g", "EXACT"),
            ("SUGAR", 6.89, "g", "EXACT"),
            ("FIBER", 1.6, "g", "EXACT"),
            ("K", 135, "mg", "EXACT"),
            ("CA", 22, "mg", "EXACT"),
            ("VITC", 31.2, "mg", "EXACT"),
            ("VITA", 58, "µg", "EXACT"),
            ("FOL", 13, "µg", "EXACT"),
        ],
    },
    # === LÉGUMES ===
    {
        "name": "Pomme de terre", "state": "raw",
        "source_id": "CIQUAL", "source_food_id": "13054",
        "source_food_name": "Pomme de terre, crue, épluchée",
        "source_country": "France",
        "mapping_score": 0.95,
        "features": "espèce=Solanum tuberosum;partie=tubercule;processing=raw",
        "conflicts": "", "review": False,
        "notes": "Pomme de terre crue moyenne, épluchée.",
        "source_version": "2024", "source_url": "https://ciqual.anses.fr/",
        "data": [
            ("ENERCKCAL", 81, "kcal", "EXACT"),
            ("WATER", 78.6, "g", "EXACT"),
            ("PROTEIN", 1.8, "g", "EXACT"),
            ("FAT", 0.1, "g", "EXACT"),
            ("CARB", 18.0, "g", "EXACT"),
            ("STARCH", 15.4, "g", "EXACT"),
            ("SUGAR", 0.9, "g", "EXACT"),
            ("FIBER", 1.5, "g", "EXACT"),
            ("K", 380, "mg", "EXACT"),
            ("NA", 4, "mg", "EXACT"),
            ("P", 50, "mg", "EXACT"),
            ("FE", 0.6, "mg", "EXACT"),
            ("VITC", 11.0, "mg", "EXACT"),
            ("VITB6", 0.3, "mg", "EXACT"),
            ("FOL", 17, "µg", "EXACT"),
        ],
    },
    {
        "name": "Oignon", "state": "raw",
        "source_id": "CIQUAL", "source_food_id": "13098",
        "source_food_name": "Oignon, cru",
        "source_country": "France",
        "mapping_score": 0.95,
        "features": "espèce=Allium cepa;partie=bulbe;processing=raw",
        "conflicts": "", "review": False,
        "notes": "Oignon cru moyen.",
        "source_version": "2024", "source_url": "https://ciqual.anses.fr/",
        "data": [
            ("ENERCKCAL", 38, "kcal", "EXACT"),
            ("WATER", 89.5, "g", "EXACT"),
            ("PROTEIN", 1.0, "g", "EXACT"),
            ("FAT", 0.1, "g", "EXACT"),
            ("CARB", 8.6, "g", "EXACT"),
            ("SUGAR", 5.2, "g", "EXACT"),
            ("FIBER", 1.6, "g", "EXACT"),
            ("K", 140, "mg", "EXACT"),
            ("CA", 25, "mg", "EXACT"),
            ("FE", 0.3, "mg", "EXACT"),
            ("VITC", 6.4, "mg", "EXACT"),
            ("VITB6", 0.12, "mg", "EXACT"),
            ("FOL", 19, "µg", "EXACT"),
        ],
    },
    {
        "name": "Ail", "state": "raw",
        "source_id": "CIQUAL", "source_food_id": "13099",
        "source_food_name": "Ail, cru",
        "source_country": "France",
        "mapping_score": 0.95,
        "features": "espèce=Allium sativum;partie=bulbe;processing=raw",
        "conflicts": "", "review": False,
        "notes": "Ail cru, gousse épluchée.",
        "source_version": "2024", "source_url": "https://ciqual.anses.fr/",
        "data": [
            ("ENERCKCAL", 149, "kcal", "EXACT"),
            ("WATER", 58.6, "g", "EXACT"),
            ("PROTEIN", 6.4, "g", "EXACT"),
            ("FAT", 0.5, "g", "EXACT"),
            ("CARB", 33.1, "g", "EXACT"),
            ("SUGAR", 1.0, "g", "EXACT"),
            ("FIBER", 2.1, "g", "EXACT"),
            ("K", 401, "mg", "EXACT"),
            ("CA", 18, "mg", "EXACT"),
            ("FE", 1.7, "mg", "EXACT"),
            ("VITC", 31.2, "mg", "EXACT"),
            ("VITB6", 1.235, "mg", "EXACT"),
            ("FOL", 3, "µg", "EXACT"),
        ],
    },
    {
        "name": "Brocoli", "state": "raw",
        "source_id": "USDAFDC", "source_food_id": "170379",
        "source_food_name": "Broccoli, raw",
        "source_country": "United States",
        "mapping_score": 0.90,
        "features": "espèce=Brassica oleracea var. italica;partie=inflorescence;processing=raw",
        "conflicts": "", "review": False,
        "notes": "Brocoli cru générique.",
        "source_version": "2024-10", "source_url": "https://fdc.nal.usda.gov/",
        "data": [
            ("ENERCKCAL", 34, "kcal", "EXACT"),
            ("WATER", 89.3, "g", "EXACT"),
            ("PROTEIN", 2.82, "g", "EXACT"),
            ("FAT", 0.37, "g", "EXACT"),
            ("CARB", 6.64, "g", "EXACT"),
            ("SUGAR", 1.7, "g", "EXACT"),
            ("FIBER", 2.6, "g", "EXACT"),
            ("K", 316, "mg", "EXACT"),
            ("CA", 47, "mg", "EXACT"),
            ("FE", 0.73, "mg", "EXACT"),
            ("VITC", 89.2, "mg", "EXACT"),
            ("VITK", 101.6, "µg", "EXACT"),
            ("FOL", 63, "µg", "EXACT"),
        ],
    },
    {
        "name": "Épinard", "state": "raw",
        "source_id": "USDAFDC", "source_food_id": "168409",
        "source_food_name": "Spinach, raw",
        "source_country": "United States",
        "mapping_score": 0.90,
        "features": "espèce=Spinacia oleracea;partie=feuille;processing=raw",
        "conflicts": "", "review": False,
        "notes": "Épinard cru, générique.",
        "source_version": "2024-10", "source_url": "https://fdc.nal.usda.gov/",
        "data": [
            ("ENERCKCAL", 23, "kcal", "EXACT"),
            ("WATER", 91.4, "g", "EXACT"),
            ("PROTEIN", 2.86, "g", "EXACT"),
            ("FAT", 0.39, "g", "EXACT"),
            ("CARB", 3.63, "g", "EXACT"),
            ("FIBER", 2.2, "g", "EXACT"),
            ("K", 558, "mg", "EXACT"),
            ("CA", 99, "mg", "EXACT"),
            ("FE", 2.71, "mg", "EXACT"),
            ("VITC", 28.1, "mg", "EXACT"),
            ("VITA", 469, "µg", "EXACT"),
            ("FOL", 194, "µg", "EXACT"),
            ("VITK", 482.9, "µg", "EXACT"),
        ],
    },
    {
        "name": "Champignon de Paris", "state": "raw",
        "source_id": "CIQUAL", "source_food_id": "13130",
        "source_food_name": "Champignon de Paris, cru",
        "source_country": "France",
        "mapping_score": 0.95,
        "features": "espèce=Agaricus bisporus;processing=raw",
        "conflicts": "", "review": False,
        "notes": "Champignon de Paris cru générique.",
        "source_version": "2024", "source_url": "https://ciqual.anses.fr/",
        "data": [
            ("ENERCKCAL", 22, "kcal", "EXACT"),
            ("WATER", 92.4, "g", "EXACT"),
            ("PROTEIN", 3.1, "g", "EXACT"),
            ("FAT", 0.34, "g", "EXACT"),
            ("CARB", 3.3, "g", "EXACT"),
            ("SUGAR", 1.98, "g", "EXACT"),
            ("FIBER", 1.0, "g", "EXACT"),
            ("K", 318, "mg", "EXACT"),
            ("NA", 5, "mg", "EXACT"),
            ("FE", 0.5, "mg", "EXACT"),
            ("VITD", 0.2, "µg", "EXACT"),
            ("RIBFL", 0.402, "mg", "EXACT"),
        ],
    },
    {
        "name": "Maïs", "state": "raw",
        "source_id": "USDAFDC", "source_food_id": "170288",
        "source_food_name": "Corn, sweet, yellow, raw",
        "source_country": "United States",
        "mapping_score": 0.90,
        "features": "espèce=Zea mays;partie=grain;processing=raw",
        "conflicts": "considéré comme céréale vs légume", "review": False,
        "notes": "Maïs doux en grain.",
        "source_version": "2024-10", "source_url": "https://fdc.nal.usda.gov/",
        "data": [
            ("ENERCKCAL", 86, "kcal", "EXACT"),
            ("WATER", 76.1, "g", "EXACT"),
            ("PROTEIN", 3.27, "g", "EXACT"),
            ("FAT", 1.35, "g", "EXACT"),
            ("CARB", 18.7, "g", "EXACT"),
            ("SUGAR", 6.26, "g", "EXACT"),
            ("FIBER", 2.0, "g", "EXACT"),
            ("K", 270, "mg", "EXACT"),
            ("NA", 15, "mg", "EXACT"),
            ("FE", 0.52, "mg", "EXACT"),
            ("VITC", 6.8, "mg", "EXACT"),
            ("THIAMIN", 0.155, "mg", "EXACT"),
            ("FOL", 42, "µg", "EXACT"),
        ],
    },
    # === LÉGUMINEUSES ===
    {
        "name": "Pois chiche sec", "state": "dried",
        "source_id": "CIQUAL", "source_food_id": "13110",
        "source_food_name": "Pois chiche, sec",
        "source_country": "France",
        "mapping_score": 0.95,
        "features": "espèce=Cicer arietinum;processing=dried",
        "conflicts": "", "review": False,
        "notes": "Pois chiche sec cru.",
        "source_version": "2024", "source_url": "https://ciqual.anses.fr/",
        "data": [
            ("ENERCKCAL", 360, "kcal", "EXACT"),
            ("WATER", 9.3, "g", "EXACT"),
            ("PROTEIN", 19.7, "g", "EXACT"),
            ("FAT", 5.4, "g", "EXACT"),
            ("CARB", 55.0, "g", "EXACT"),
            ("SUGAR", 7.5, "g", "EXACT"),
            ("STARCH", 41.0, "g", "EXACT"),
            ("FIBER", 12.2, "g", "EXACT"),
            ("K", 900, "mg", "EXACT"),
            ("FE", 5.4, "mg", "EXACT"),
            ("MG", 120, "mg", "EXACT"),
            ("FOL", 350, "µg", "EXACT"),
        ],
    },
    {
        "name": "Lentille verte sec", "state": "dried",
        "source_id": "CIQUAL", "source_food_id": "13111",
        "source_food_name": "Lentille, sèche",
        "source_country": "France",
        "mapping_score": 0.95,
        "features": "espèce=Lens culinaris;processing=dried",
        "conflicts": "", "review": False,
        "notes": "Lentille verte sèche.",
        "source_version": "2024", "source_url": "https://ciqual.anses.fr/",
        "data": [
            ("ENERCKCAL", 350, "kcal", "EXACT"),
            ("WATER", 9.0, "g", "EXACT"),
            ("PROTEIN", 23.4, "g", "EXACT"),
            ("FAT", 1.6, "g", "EXACT"),
            ("CARB", 56.0, "g", "EXACT"),
            ("STARCH", 42.0, "g", "EXACT"),
            ("FIBER", 11.5, "g", "EXACT"),
            ("FE", 7.0, "mg", "EXACT"),
            ("K", 820, "mg", "EXACT"),
            ("FOL", 350, "µg", "EXACT"),
        ],
    },
    {
        "name": "Haricot rouge sec", "state": "dried",
        "source_id": "USDAFDC", "source_food_id": "173757",
        "source_food_name": "Beans, kidney, all types, mature seeds, raw",
        "source_country": "United States",
        "mapping_score": 0.90,
        "features": "espèce=Phaseolus vulgaris;processing=dried",
        "conflicts": "", "review": False,
        "notes": "Haricot rouge sec cru.",
        "source_version": "2024-10", "source_url": "https://fdc.nal.usda.gov/",
        "data": [
            ("ENERCKCAL", 333, "kcal", "EXACT"),
            ("WATER", 11.8, "g", "EXACT"),
            ("PROTEIN", 23.6, "g", "EXACT"),
            ("FAT", 0.83, "g", "EXACT"),
            ("CARB", 60.0, "g", "EXACT"),
            ("FIBER", 24.9, "g", "EXACT"),
            ("K", 1359, "mg", "EXACT"),
            ("FE", 8.2, "mg", "EXACT"),
            ("FOL", 394, "µg", "EXACT"),
        ],
    },
    {
        "name": "Soja", "state": "dried",
        "source_id": "USDAFDC", "source_food_id": "174270",
        "source_food_name": "Soybeans, mature seeds, raw",
        "source_country": "United States",
        "mapping_score": 0.90,
        "features": "espèce=Glycine max;processing=dried",
        "conflicts": "", "review": False,
        "notes": "Soja sec cru.",
        "source_version": "2024-10", "source_url": "https://fdc.nal.usda.gov/",
        "data": [
            ("ENERCKCAL", 446, "kcal", "EXACT"),
            ("WATER", 8.5, "g", "EXACT"),
            ("PROTEIN", 36.5, "g", "EXACT"),
            ("FAT", 20.0, "g", "EXACT"),
            ("CARB", 30.2, "g", "EXACT"),
            ("FIBER", 9.3, "g", "EXACT"),
            ("K", 1797, "mg", "EXACT"),
            ("CA", 277, "mg", "EXACT"),
            ("FE", 15.7, "mg", "EXACT"),
            ("VITK", 47.0, "µg", "EXACT"),
        ],
    },
    # === VIANDES ===
    {
        "name": "Bœuf (viande)", "state": "raw",
        "source_id": "CIQUAL", "source_food_id": "61000",
        "source_food_name": "Bœuf, viande crue, moyenne (5-10% MG)",
        "source_country": "France",
        "mapping_score": 0.90,
        "features": "espèce=Bos taurus;partie=muscle;processing=raw",
        "conflicts": "Composition variable selon race, morceau, persillage", "review": True,
        "notes": "Bœuf viande moyenne, 5-10% MG. Variabilité élevée ; à affiner par morceau.",
        "source_version": "2024", "source_url": "https://ciqual.anses.fr/",
        "data": [
            ("ENERCKCAL", 220, "kcal", "EXACT"),
            ("WATER", 65.0, "g", "EXACT"),
            ("PROTEIN", 20.0, "g", "EXACT"),
            ("FAT", 14.0, "g", "EXACT"),
            ("FAT_SAT", 6.0, "g", "EXACT"),
            ("CHOLEST", 70, "mg", "EXACT"),
            ("NA", 70, "mg", "EXACT"),
            ("K", 330, "mg", "EXACT"),
            ("FE", 2.5, "mg", "EXACT"),
            ("ZN", 4.5, "mg", "EXACT"),
            ("VITB12", 2.5, "µg", "EXACT"),
            ("VITB6", 0.4, "mg", "EXACT"),
            ("FOL", 8, "µg", "EXACT"),
        ],
    },
    {
        "name": "Porc (viande)", "state": "raw",
        "source_id": "CIQUAL", "source_food_id": "61500",
        "source_food_name": "Porc, viande crue, moyenne",
        "source_country": "France",
        "mapping_score": 0.90,
        "features": "espèce=Sus scrofa;partie=muscle;processing=raw",
        "conflicts": "Composition très variable selon morceau", "review": True,
        "notes": "Porc moyenne toutes pièces.",
        "source_version": "2024", "source_url": "https://ciqual.anses.fr/",
        "data": [
            ("ENERCKCAL", 242, "kcal", "EXACT"),
            ("WATER", 60.0, "g", "EXACT"),
            ("PROTEIN", 18.5, "g", "EXACT"),
            ("FAT", 18.0, "g", "EXACT"),
            ("FAT_SAT", 6.5, "g", "EXACT"),
            ("CHOLEST", 70, "mg", "EXACT"),
            ("NA", 60, "mg", "EXACT"),
            ("FE", 1.0, "mg", "EXACT"),
            ("ZN", 2.0, "mg", "EXACT"),
            ("THIAMIN", 0.7, "mg", "EXACT"),
            ("VITB6", 0.4, "mg", "EXACT"),
            ("VITB12", 1.0, "µg", "EXACT"),
        ],
    },
    {
        "name": "Agneau (viande)", "state": "raw",
        "source_id": "USDAFDC", "source_food_id": "170609",
        "source_food_name": "Lamb, domestic, composite of trimmed retail cuts, separable lean and fat, trimmed to 1/4\" fat, choice, raw",
        "source_country": "United States",
        "mapping_score": 0.85,
        "features": "espèce=Ovis aries;processing=raw",
        "conflicts": "Morceau variable", "review": True,
        "notes": "Agneau moyenne US.",
        "source_version": "2024-10", "source_url": "https://fdc.nal.usda.gov/",
        "data": [
            ("ENERCKCAL", 282, "kcal", "EXACT"),
            ("WATER", 57.8, "g", "EXACT"),
            ("PROTEIN", 16.6, "g", "EXACT"),
            ("FAT", 23.4, "g", "EXACT"),
            ("FAT_SAT", 10.0, "g", "EXACT"),
            ("CHOLEST", 72, "mg", "EXACT"),
            ("FE", 1.6, "mg", "EXACT"),
            ("ZN", 3.0, "mg", "EXACT"),
            ("VITB12", 2.0, "µg", "EXACT"),
        ],
    },
    {
        "name": "Saumon", "state": "raw",
        "source_id": "USDAFDC", "source_food_id": "173686",
        "source_food_name": "Fish, salmon, atlantic, wild, raw",
        "source_country": "United States",
        "mapping_score": 0.85,
        "features": "espèce=Salmo salar;processing=raw;form=filet",
        "conflicts": "espèce précise variable (Atlantique vs Pacifique)", "review": True,
        "notes": "Wild atlantic generic. Variabilité inter-espèces à valider.",
        "source_version": "2024-10", "source_url": "https://fdc.nal.usda.gov/",
        "data": [
            ("ENERCKCAL", 208, "kcal", "EXACT"),
            ("WATER", 64.0, "g", "EXACT"),
            ("PROTEIN", 20.4, "g", "EXACT"),
            ("FAT", 13.4, "g", "EXACT"),
            ("FAT_SAT", 3.1, "g", "EXACT"),
            ("OMEGA3", 1.9, "g", "EXACT"),
            ("CHOLEST", 55, "mg", "EXACT"),
            ("NA", 59, "mg", "EXACT"),
            ("P", 240, "mg", "EXACT"),
            ("K", 363, "mg", "EXACT"),
            ("VITD", 13.1, "µg", "EXACT"),
            ("VITB12", 3.2, "µg", "EXACT"),
        ],
    },
    {
        "name": "Thon", "state": "raw",
        "source_id": "USDAFDC", "source_food_id": "173713",
        "source_food_name": "Fish, tuna, fresh, raw",
        "source_country": "United States",
        "mapping_score": 0.85,
        "features": "espèce=Thunnus;processing=raw;form=filet",
        "conflicts": "espèce précise variable (yellowfin, albacore, etc.)", "review": True,
        "notes": "Variabilité espèce → conservateur ; valeurs à valider au cas par cas.",
        "source_version": "2024-10", "source_url": "https://fdc.nal.usda.gov/",
        "data": [
            ("ENERCKCAL", 144, "kcal", "EXACT"),
            ("WATER", 68.0, "g", "EXACT"),
            ("PROTEIN", 23.3, "g", "EXACT"),
            ("FAT", 4.9, "g", "EXACT"),
            ("FAT_SAT", 1.3, "g", "EXACT"),
            ("OMEGA3", 0.5, "g", "EXACT"),
            ("CHOLEST", 38, "mg", "EXACT"),
            ("NA", 39, "mg", "EXACT"),
            ("P", 269, "mg", "EXACT"),
            ("K", 252, "mg", "EXACT"),
            ("VITD", 1.7, "µg", "EXACT"),
            ("VITB12", 1.9, "µg", "EXACT"),
        ],
    },
    {
        "name": "Cabillaud", "state": "raw",
        "source_id": "USDAFDC", "source_food_id": "175117",
        "source_food_name": "Fish, cod, atlantic, raw",
        "source_country": "United States",
        "mapping_score": 0.85,
        "features": "espèce=Gadus morhua;processing=raw",
        "conflicts": "", "review": False,
        "notes": "Cabillaud cru générique.",
        "source_version": "2024-10", "source_url": "https://fdc.nal.usda.gov/",
        "data": [
            ("ENERCKCAL", 82, "kcal", "EXACT"),
            ("WATER", 81.2, "g", "EXACT"),
            ("PROTEIN", 17.8, "g", "EXACT"),
            ("FAT", 0.67, "g", "EXACT"),
            ("CHOLEST", 43, "mg", "EXACT"),
            ("NA", 78, "mg", "EXACT"),
            ("P", 203, "mg", "EXACT"),
            ("K", 413, "mg", "EXACT"),
            ("VITB12", 0.91, "µg", "EXACT"),
        ],
    },
    # === FRUITS À COQUE ===
    {
        "name": "Noisette", "state": "raw",
        "source_id": "USDAFDC", "source_food_id": "170581",
        "source_food_name": "Nuts, hazelnuts or filberts, raw",
        "source_country": "United States",
        "mapping_score": 0.90,
        "features": "espèce=Corylus avellana;processing=raw",
        "conflicts": "", "review": False,
        "notes": "Noisette crue générique.",
        "source_version": "2024-10", "source_url": "https://fdc.nal.usda.gov/",
        "data": [
            ("ENERCKCAL", 628, "kcal", "EXACT"),
            ("WATER", 5.3, "g", "EXACT"),
            ("PROTEIN", 14.96, "g", "EXACT"),
            ("FAT", 60.75, "g", "EXACT"),
            ("FAT_SAT", 4.46, "g", "EXACT"),
            ("FAT_MONO", 45.65, "g", "EXACT"),
            ("FAT_POLY", 7.92, "g", "EXACT"),
            ("CARB", 16.7, "g", "EXACT"),
            ("FIBER", 9.7, "g", "EXACT"),
            ("MG", 163, "mg", "EXACT"),
            ("P", 290, "mg", "EXACT"),
            ("VITE", 15.0, "mg", "EXACT"),
        ],
    },
    {
        "name": "Noix", "state": "raw",
        "source_id": "USDAFDC", "source_food_id": "170569",
        "source_food_name": "Nuts, walnuts, english, raw",
        "source_country": "United States",
        "mapping_score": 0.90,
        "features": "espèce=Juglans regia;processing=raw",
        "conflicts": "", "review": False,
        "notes": "Noix crue générique.",
        "source_version": "2024-10", "source_url": "https://fdc.nal.usda.gov/",
        "data": [
            ("ENERCKCAL", 654, "kcal", "EXACT"),
            ("WATER", 4.1, "g", "EXACT"),
            ("PROTEIN", 15.23, "g", "EXACT"),
            ("FAT", 65.21, "g", "EXACT"),
            ("FAT_SAT", 6.13, "g", "EXACT"),
            ("OMEGA3", 9.08, "g", "EXACT"),
            ("OMEGA6", 38.09, "g", "EXACT"),
            ("CARB", 13.71, "g", "EXACT"),
            ("FIBER", 6.7, "g", "EXACT"),
            ("MG", 158, "mg", "EXACT"),
            ("P", 346, "mg", "EXACT"),
            ("VITE", 0.7, "mg", "EXACT"),
        ],
    },
    {
        "name": "Pistache", "state": "raw",
        "source_id": "USDAFDC", "source_food_id": "170574",
        "source_food_name": "Nuts, pistachio nuts, raw",
        "source_country": "United States",
        "mapping_score": 0.90,
        "features": "espèce=Pistacia vera;processing=raw",
        "conflicts": "", "review": False,
        "notes": "Pistache crue générique.",
        "source_version": "2024-10", "source_url": "https://fdc.nal.usda.gov/",
        "data": [
            ("ENERCKCAL", 560, "kcal", "EXACT"),
            ("WATER", 4.3, "g", "EXACT"),
            ("PROTEIN", 20.27, "g", "EXACT"),
            ("FAT", 45.97, "g", "EXACT"),
            ("CARB", 28.28, "g", "EXACT"),
            ("FIBER", 10.3, "g", "EXACT"),
            ("K", 1025, "mg", "EXACT"),
            ("P", 490, "mg", "EXACT"),
            ("VITB6", 1.7, "mg", "EXACT"),
            ("VITE", 2.3, "mg", "EXACT"),
        ],
    },
    # === CÉRÉALES ===
    {
        "name": "Avoine", "state": "dried",
        "source_id": "USDAFDC", "source_food_id": "173904",
        "source_food_name": "Oats, raw, whole",
        "source_country": "United States",
        "mapping_score": 0.85,
        "features": "espèce=Avena sativa;processing=raw grain",
        "conflicts": "", "review": False,
        "notes": "Avoine grain entier cru.",
        "source_version": "2024-10", "source_url": "https://fdc.nal.usda.gov/",
        "data": [
            ("ENERCKCAL", 389, "kcal", "EXACT"),
            ("WATER", 8.2, "g", "EXACT"),
            ("PROTEIN", 16.89, "g", "EXACT"),
            ("FAT", 6.9, "g", "EXACT"),
            ("CARB", 66.27, "g", "EXACT"),
            ("FIBER", 10.6, "g", "EXACT"),
            ("MG", 138, "mg", "EXACT"),
            ("P", 523, "mg", "EXACT"),
            ("FE", 4.72, "mg", "EXACT"),
        ],
    },
    {
        "name": "Quinoa", "state": "dried",
        "source_id": "USDAFDC", "source_food_id": "169736",
        "source_food_name": "Quinoa, raw, white",
        "source_country": "United States",
        "mapping_score": 0.85,
        "features": "espèce=Chenopodium quinoa;processing=raw grain",
        "conflicts": "", "review": False,
        "notes": "Quinoa blanc grain cru.",
        "source_version": "2024-10", "source_url": "https://fdc.nal.usda.gov/",
        "data": [
            ("ENERCKCAL", 368, "kcal", "EXACT"),
            ("WATER", 8.6, "g", "EXACT"),
            ("PROTEIN", 14.12, "g", "EXACT"),
            ("FAT", 6.07, "g", "EXACT"),
            ("CARB", 64.16, "g", "EXACT"),
            ("FIBER", 7.0, "g", "EXACT"),
            ("MG", 197, "mg", "EXACT"),
            ("FE", 4.57, "mg", "EXACT"),
            ("FOL", 184, "µg", "EXACT"),
        ],
    },
    # === PRODUITS LAITIERS ===
    {
        "name": "Yaourt nature", "state": "fermented",
        "source_id": "CIQUAL", "source_food_id": "19500",
        "source_food_name": "Yaourt nature, non sucré, au lait entier",
        "source_country": "France",
        "mapping_score": 0.95,
        "features": "espèce=Bos taurus;processing=fermented",
        "conflicts": "", "review": False,
        "notes": "Yaourt nature non sucré au lait entier.",
        "source_version": "2024", "source_url": "https://ciqual.anses.fr/",
        "data": [
            ("ENERCKCAL", 60, "kcal", "EXACT"),
            ("WATER", 87.5, "g", "EXACT"),
            ("PROTEIN", 3.5, "g", "EXACT"),
            ("FAT", 3.0, "g", "EXACT"),
            ("CARB", 4.5, "g", "EXACT"),
            ("SUGAR", 4.5, "g", "EXACT"),
            ("LACTOSE", 4.0, "g", "EXACT"),
            ("CA", 120, "mg", "EXACT"),
            ("P", 90, "mg", "EXACT"),
            ("RIBFL", 0.18, "mg", "EXACT"),
            ("VITB12", 0.4, "µg", "EXACT"),
        ],
    },
    {
        "name": "Mozzarella", "state": "raw",
        "source_id": "CIQUAL", "source_food_id": "19600",
        "source_food_name": "Mozzarella, au lait de vache",
        "source_country": "France",
        "mapping_score": 0.90,
        "features": "espèce=Bos taurus;processing=filée",
        "conflicts": "", "review": False,
        "notes": "Mozzarella vache générique.",
        "source_version": "2024", "source_url": "https://ciqual.anses.fr/",
        "data": [
            ("ENERCKCAL", 250, "kcal", "EXACT"),
            ("WATER", 50.0, "g", "EXACT"),
            ("PROTEIN", 22.0, "g", "EXACT"),
            ("FAT", 17.0, "g", "EXACT"),
            ("FAT_SAT", 11.0, "g", "EXACT"),
            ("CA", 500, "mg", "EXACT"),
            ("P", 380, "mg", "EXACT"),
            ("NA", 500, "mg", "EXACT"),
            ("VITB12", 1.5, "µg", "EXACT"),
        ],
    },
    {
        "name": "Parmigiano Reggiano", "state": "raw",
        "source_id": "USDAFDC", "source_food_id": "170892",
        "source_food_name": "Cheese, parmesan, hard",
        "source_country": "United States",
        "mapping_score": 0.85,
        "features": "espèce=Bos taurus;processing=aged hard",
        "conflicts": "", "review": False,
        "notes": "Parmesan générique (équivalent Parmigiano Reggiano, AOP).",
        "source_version": "2024-10", "source_url": "https://fdc.nal.usda.gov/",
        "data": [
            ("ENERCKCAL", 431, "kcal", "EXACT"),
            ("WATER", 32.0, "g", "EXACT"),
            ("PROTEIN", 38.46, "g", "EXACT"),
            ("FAT", 28.61, "g", "EXACT"),
            ("FAT_SAT", 19.05, "g", "EXACT"),
            ("CHOLEST", 88, "mg", "EXACT"),
            ("CA", 1184, "mg", "EXACT"),
            ("P", 694, "mg", "EXACT"),
            ("NA", 1804, "mg", "EXACT"),
            ("VITB12", 1.2, "µg", "EXACT"),
        ],
    },
    {
        "name": "Cheddar", "state": "raw",
        "source_id": "USDAFDC", "source_food_id": "173420",
        "source_food_name": "Cheese, cheddar",
        "source_country": "United States",
        "mapping_score": 0.90,
        "features": "espèce=Bos taurus;processing=aged",
        "conflicts": "", "review": False,
        "notes": "Cheddar générique.",
        "source_version": "2024-10", "source_url": "https://fdc.nal.usda.gov/",
        "data": [
            ("ENERCKCAL", 403, "kcal", "EXACT"),
            ("WATER", 36.4, "g", "EXACT"),
            ("PROTEIN", 22.87, "g", "EXACT"),
            ("FAT", 33.31, "g", "EXACT"),
            ("FAT_SAT", 21.0, "g", "EXACT"),
            ("CA", 721, "mg", "EXACT"),
            ("P", 512, "mg", "EXACT"),
            ("NA", 653, "mg", "EXACT"),
            ("VITB12", 1.1, "µg", "EXACT"),
        ],
    },
    # === HUILES ===
    {
        "name": "Huile de tournesol", "state": "extracted",
        "source_id": "CIQUAL", "source_food_id": "17020",
        "source_food_name": "Huile de tournesol",
        "source_country": "France",
        "mapping_score": 0.95,
        "features": "espèce=Helianthus annuus;processing=refined",
        "conflicts": "", "review": False,
        "notes": "Huile de tournesol raffinée.",
        "source_version": "2024", "source_url": "https://ciqual.anses.fr/",
        "data": [
            ("ENERCKCAL", 900, "kcal", "EXACT"),
            ("WATER", 0.05, "g", "EXACT"),
            ("FAT", 100, "g", "EXACT"),
            ("FAT_SAT", 10.3, "g", "EXACT"),
            ("FAT_MONO", 19.5, "g", "EXACT"),
            ("FAT_POLY", 65.7, "g", "EXACT"),
            ("OMEGA6", 65.7, "g", "EXACT"),
            ("VITE", 49, "mg", "EXACT"),
        ],
    },
    {
        "name": "Huile de colza", "state": "extracted",
        "source_id": "CIQUAL", "source_food_id": "17030",
        "source_food_name": "Huile de colza",
        "source_country": "France",
        "mapping_score": 0.95,
        "features": "espèce=Brassica napus;processing=refined",
        "conflicts": "", "review": False,
        "notes": "Huile de colza raffinée.",
        "source_version": "2024", "source_url": "https://ciqual.anses.fr/",
        "data": [
            ("ENERCKCAL", 900, "kcal", "EXACT"),
            ("WATER", 0.05, "g", "EXACT"),
            ("FAT", 100, "g", "EXACT"),
            ("FAT_SAT", 7.4, "g", "EXACT"),
            ("FAT_MONO", 58.8, "g", "EXACT"),
            ("FAT_POLY", 28.2, "g", "EXACT"),
            ("OMEGA3", 9.1, "g", "EXACT"),
            ("OMEGA6", 17.8, "g", "EXACT"),
            ("VITE", 17, "mg", "EXACT"),
        ],
    },
    # === CONDIMENTS ===
    {
        "name": "Sauce soja", "state": "fermented",
        "source_id": "USDAFDC", "source_food_id": "171115",
        "source_food_name": "Soy sauce made from soy and wheat (shoyu)",
        "source_country": "United States",
        "mapping_score": 0.85,
        "features": "espèce=Glycine max;processing=fermented",
        "conflicts": "", "review": False,
        "notes": "Shoyu générique.",
        "source_version": "2024-10", "source_url": "https://fdc.nal.usda.gov/",
        "data": [
            ("ENERCKCAL", 53, "kcal", "EXACT"),
            ("WATER", 70.0, "g", "EXACT"),
            ("PROTEIN", 8.14, "g", "EXACT"),
            ("FAT", 0.57, "g", "EXACT"),
            ("CARB", 4.93, "g", "EXACT"),
            ("NA", 5715, "mg", "EXACT"),  # Très riche en sodium !
            ("K", 212, "mg", "EXACT"),
            ("MG", 35, "mg", "EXACT"),
        ],
    },
    {
        "name": "Moutarde de Dijon", "state": "processed",
        "source_id": "CIQUAL", "source_food_id": "11000",
        "source_food_name": "Moutarde de Dijon",
        "source_country": "France",
        "mapping_score": 0.90,
        "features": "espèce=Sinapis;processing=ground",
        "conflicts": "", "review": False,
        "notes": "Moutarde de Dijon générique.",
        "source_version": "2024", "source_url": "https://ciqual.anses.fr/",
        "data": [
            ("ENERCKCAL", 70, "kcal", "EXACT"),
            ("WATER", 82.0, "g", "EXACT"),
            ("PROTEIN", 4.4, "g", "EXACT"),
            ("FAT", 4.0, "g", "EXACT"),
            ("CARB", 6.0, "g", "EXACT"),
            ("SUGAR", 4.0, "g", "EXACT"),
            ("NA", 1200, "mg", "EXACT"),
            ("K", 140, "mg", "EXACT"),
            ("CA", 50, "mg", "EXACT"),
        ],
    },
    # === BOISSONS ===
    {
        "name": "Bière blonde (lager)", "state": "fermented",
        "source_id": "USDAFDC", "source_food_id": "170485",
        "source_food_name": "Alcoholic beverage, beer, regular, all",
        "source_country": "United States",
        "mapping_score": 0.80,
        "features": "espèce=Hordeum vulgare;processing=fermented;forme=liquid",
        "conflicts": "Teneur en alcool variable selon style (3-7%)", "review": True,
        "notes": "Bière moyenne, ABV ~5%. Considérer variabilité.",
        "source_version": "2024-10", "source_url": "https://fdc.nal.usda.gov/",
        "data": [
            ("ENERCKCAL", 43, "kcal", "EXACT"),
            ("WATER", 91.0, "g", "EXACT"),
            ("ALCOHOL", 3.9, "g", "EXACT"),
            ("PROTEIN", 0.46, "g", "EXACT"),
            ("CARB", 3.55, "g", "EXACT"),
            ("NA", 4, "mg", "EXACT"),
            ("K", 27, "mg", "EXACT"),
            ("MG", 6, "mg", "EXACT"),
        ],
    },
    {
        "name": "Vin blanc sec", "state": "fermented",
        "source_id": "CIQUAL", "source_food_id": "52100",
        "source_food_name": "Vin blanc sec",
        "source_country": "France",
        "mapping_score": 0.95,
        "features": "espèce=Vitis vinifera;processing=fermented",
        "conflicts": "", "review": False,
        "notes": "Vin blanc sec 12% vol.",
        "source_version": "2024", "source_url": "https://ciqual.anses.fr/",
        "data": [
            ("ENERCKCAL", 73, "kcal", "EXACT"),
            ("WATER", 88.0, "g", "EXACT"),
            ("ALCOHOL", 9.0, "g", "EXACT"),
            ("PROTEIN", 0.07, "g", "EXACT"),
            ("CARB", 2.6, "g", "EXACT"),
            ("NA", 2, "mg", "EXACT"),
            ("K", 71, "mg", "EXACT"),
        ],
    },
    # === SUCRES & EXTRAR ===
    {
        "name": "Sirop d'érable", "state": "boiled",
        "source_id": "USDAFDC", "source_food_id": "169711",
        "source_food_name": "Syrups, maple",
        "source_country": "United States",
        "mapping_score": 0.90,
        "features": "espèce=Acer saccharum;processing=boiled down",
        "conflicts": "", "review": False,
        "notes": "Sirop d'érable pur.",
        "source_version": "2024-10", "source_url": "https://fdc.nal.usda.gov/",
        "data": [
            ("ENERCKCAL", 260, "kcal", "EXACT"),
            ("WATER", 32.4, "g", "EXACT"),
            ("CARB", 67.0, "g", "EXACT"),
            ("SUGAR", 60.5, "g", "EXACT"),
            ("SUCROSE", 58.0, "g", "EXACT"),
            ("K", 212, "mg", "EXACT"),
            ("CA", 102, "mg", "EXACT"),
            ("FE", 0.11, "mg", "EXACT"),
            ("ZN", 1.47, "mg", "EXACT"),
        ],
    },
    {
        "name": "Chocolat noir 85%", "state": "conched",
        "source_id": "USDAFDC", "source_food_id": "170272",
        "source_food_name": "Dark chocolate 70-85% cacao",
        "source_country": "United States",
        "mapping_score": 0.85,
        "features": "espèce=Theobroma cacao;cocoa%=70-85",
        "conflicts": "", "review": False,
        "notes": "Chocolat noir 70-85% générique, USDA.",
        "source_version": "2024-10", "source_url": "https://fdc.nal.usda.gov/",
        "data": [
            ("ENERCKCAL", 605, "kcal", "EXACT"),
            ("WATER", 1.0, "g", "EXACT"),
            ("PROTEIN", 8.0, "g", "EXACT"),
            ("FAT", 45.0, "g", "EXACT"),
            ("FAT_SAT", 27.0, "g", "EXACT"),
            ("CARB", 41.0, "g", "EXACT"),
            ("SUGAR", 16.0, "g", "EXACT"),
            ("FIBER", 13.0, "g", "EXACT"),
            ("FE", 13.0, "mg", "EXACT"),
            ("MG", 240, "mg", "EXACT"),
            ("K", 750, "mg", "EXACT"),
            ("THEOBROM", 900, "mg", "EXACT"),
            ("CAFFEINE", 75, "mg", "EXACT"),
        ],
    },
    {
        "name": "Cacao en poudre", "state": "powder",
        "source_id": "USDAFDC", "source_food_id": "169592",
        "source_food_name": "Cocoa, dry powder, unsweetened",
        "source_country": "United States",
        "mapping_score": 0.90,
        "features": "espèce=Theobroma cacao;processing=beans defatted dried ground",
        "conflicts": "", "review": False,
        "notes": "Cacao en poudre non sucré.",
        "source_version": "2024-10", "source_url": "https://fdc.nal.usda.gov/",
        "data": [
            ("ENERCKCAL", 228, "kcal", "EXACT"),
            ("WATER", 3.0, "g", "EXACT"),
            ("PROTEIN", 19.6, "g", "EXACT"),
            ("FAT", 13.7, "g", "EXACT"),
            ("FAT_SAT", 8.07, "g", "EXACT"),
            ("CARB", 57.9, "g", "EXACT"),
            ("FIBER", 37.0, "g", "EXACT"),
            ("FE", 13.86, "mg", "EXACT"),
            ("MG", 499, "mg", "EXACT"),
            ("K", 1524, "mg", "EXACT"),
            ("THEOBROM", 2057, "mg", "EXACT"),
            ("CAFFEINE", 230, "mg", "EXACT"),
            ("POLYPHEN", 5000, "mg", "ESTIMATED"),
        ],
    },
    # === EXTRA : autres produits animaux courants ===
    {
        "name": "Crevette", "state": "raw",
        "source_id": "USDAFDC", "source_food_id": "175170",
        "source_food_name": "Crustaceans, shrimp, raw",
        "source_country": "United States",
        "mapping_score": 0.85,
        "features": "espèce=Penaeus;processing=raw",
        "conflicts": "", "review": False,
        "notes": "Crevette crue générique.",
        "source_version": "2024-10", "source_url": "https://fdc.nal.usda.gov/",
        "data": [
            ("ENERCKCAL", 99, "kcal", "EXACT"),
            ("WATER", 75.9, "g", "EXACT"),
            ("PROTEIN", 24.0, "g", "EXACT"),
            ("FAT", 0.32, "g", "EXACT"),
            ("CHOLEST", 189, "mg", "EXACT"),
            ("NA", 111, "mg", "EXACT"),
            ("P", 237, "mg", "EXACT"),
            ("K", 259, "mg", "EXACT"),
            ("VITB12", 1.86, "µg", "EXACT"),
            ("OMEGA3", 0.04, "g", "EXACT"),
        ],
    },
    {
        "name": "Moule", "state": "raw",
        "source_id": "CIQUAL", "source_food_id": "81100",
        "source_food_name": "Moule, crue",
        "source_country": "France",
        "mapping_score": 0.90,
        "features": "espèce=Mytilus edulis;processing=raw",
        "conflicts": "", "review": False,
        "notes": "Moule crue générique.",
        "source_version": "2024", "source_url": "https://ciqual.anses.fr/",
        "data": [
            ("ENERCKCAL", 86, "kcal", "EXACT"),
            ("WATER", 80.6, "g", "EXACT"),
            ("PROTEIN", 11.9, "g", "EXACT"),
            ("FAT", 2.3, "g", "EXACT"),
            ("FAT_SAT", 0.4, "g", "EXACT"),
            ("OMEGA3", 0.5, "g", "EXACT"),
            ("CHOLEST", 28, "mg", "EXACT"),
            ("NA", 290, "mg", "EXACT"),
            ("FE", 4.5, "mg", "EXACT"),
            ("VITB12", 24.0, "µg", "EXACT"),
            ("ZN", 2.0, "mg", "EXACT"),
        ],
    },
    {
        "name": "Anchois", "state": "raw",
        "source_id": "USDAFDC", "source_food_id": "174163",
        "source_food_name": "Fish, anchovy, european, raw",
        "source_country": "United States",
        "mapping_score": 0.85,
        "features": "espèce=Engraulis encrasicolus;processing=raw",
        "conflicts": "", "review": False,
        "notes": "Anchois cru générique.",
        "source_version": "2024-10", "source_url": "https://fdc.nal.usda.gov/",
        "data": [
            ("ENERCKCAL", 131, "kcal", "EXACT"),
            ("WATER", 71.0, "g", "EXACT"),
            ("PROTEIN", 20.4, "g", "EXACT"),
            ("FAT", 4.84, "g", "EXACT"),
            ("FAT_SAT", 1.18, "g", "EXACT"),
            ("OMEGA3", 1.45, "g", "EXACT"),
            ("CHOLEST", 60, "mg", "EXACT"),
            ("NA", 104, "mg", "EXACT"),
            ("P", 252, "mg", "EXACT"),
            ("K", 383, "mg", "EXACT"),
            ("VITD", 2.0, "µg", "EXACT"),
        ],
    },
    {
        "name": "Cacao boisson non formulé", "state": "brewed",
        "source_id": "CIQUAL", "source_food_id": "19050",
        "source_food_name": "Chocolat chaud, à l'eau",
        "source_country": "France",
        "mapping_score": 0.85,
        "features": "espèce=Theobroma cacao;processing=brewed;form=liquid",
        "conflicts": "", "review": False,
        "notes": "Boisson chocolatée non formulée (cacao+eau+sucre).",
        "source_version": "2024", "source_url": "https://ciqual.anses.fr/",
        "data": [
            ("ENERCKCAL", 65, "kcal", "EXACT"),
            ("WATER", 86.0, "g", "EXACT"),
            ("PROTEIN", 2.1, "g", "EXACT"),
            ("FAT", 1.5, "g", "EXACT"),
            ("CARB", 11.0, "g", "EXACT"),
            ("SUGAR", 10.0, "g", "EXACT"),
            ("CA", 60, "mg", "EXACT"),
            ("FE", 0.7, "mg", "EXACT"),
            ("MG", 30, "mg", "EXACT"),
            ("THEOBROM", 60, "mg", "EXACT"),
            ("CAFFEINE", 5, "mg", "EXACT"),
        ],
    },
]
